League\OAuth2\Server\Entity\AccessTokenEntity:
  type:             entity
  table:            oauth_access_token
  repositoryClass:  Tonis\OAuth2\Storage\Doctrine\ORM\AccessToken
  id:
    id:
      type: string
  fields:
    expireTime:
      type: datetime
      column: expire_time
  manyToOne:
      session:
        targetEntity: League\OAuth2\Server\Entity\SessionEntity
        fetch: EAGER
