League\OAuth2\Server\Entity\RefreshTokenEntity:
  type:             entity
  table:            oauth_refresh_token
  repositoryClass:  Tonis\OAuth2\Storage\Doctrine\ORM\RefreshToken
  id:
    id:
      type: string
  fields:
    expireTime:
      type: datetime
      column: expire_time
  manyToOne:
      session:
        targetEntity: League\OAuth2\Server\Entity\SessionEntity
