Tonis\OAuth2\Entity\OAuthAccessToken:
  type:             entity
  table:            oauth_access_token
  repositoryClass:  Tonis\OAuth2\Repository\OAuthAccessToken
  id:
    id:
      type:   integer
      options:
        unsigned: true
      generator:
        strategy: AUTO
  fields:
    token:
      type:   string
      length: 40
      unique: true
    expires:
      type: datetime
    scope:
      type:     string
      length:   50
      nullable: true
  manyToOne:
    client:
      targetEntity: Tonis\OAuth2\Entity\OAuthClientInterface
      joinColumn:
        name:                 client_id
        referencedColumnName: id
        nullable:             false
    user:
      targetEntity: Tonis\OAuth2\Entity\OAuthUserInterface
      joinColumn:
        name:                 user_id
        referencedColumnName: id