Tonis\OAuth2\Doctrine\Entity\Scope:
  type: entity
  table: oauth_scope
  repositoryClass: Tonis\OAuth2\Doctrine\Repository\Scope
  id:
    id:
      type: string
      column: scope
  fields:
    isDefault:
      type: boolean
      column: is_default
    description:
      type: string
      length: 4000
      nullable: true
