Tonis\OAuth2\Entity\OAuthClient:
  type:             entity
  table:            oauth_client
  repositoryClass:  Tonis\OAuth2\Repository\OAuthClient
  id:
    id:
      type: integer
      options:
        unsigned: true
      generator:
        strategy: AUTO
  fields:
    clientId:
      type:   string
      length: 50
      unique: true
      column: client_id
    clientSecret:
      type:   string
      length: 100
      column: client_secret
    redirectUri:
      column:   redirect_uri
      type:     string
      length:   255
      nullable: true
