Tonis\OAuth2\Doctrine\Entity\AccessToken:
  type: entity
  table: oauth_access_token
  repositoryClass: Tonis\OAuth2\Doctrine\Repository\AccessToken
  id:
    token:
      type: string
      length: 40
      column: access_token
  fields:
    expires:
      type: datetime
    scope:
      type: string
      length: 4000
      nullable: true
  manyToOne:
      client:
        targetEntity: Tonis\OAuth2\Doctrine\Entity\Client
        joinColumn:
          referencedColumnName: client_id
          nullable: false
      user:
        targetEntity: Tonis\OAuth2\Doctrine\Entity\User